server:
  port: 1112
spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/db_review
    driver-class-name: org.postgresql.Driver
    username: sa
    password: 123456
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
    generate-ddl: true
  thymeleaf:
    cache: false
